board/urls.py
from django.urls import path
from . import views

app_name = 'board'
urlpatterns = [
    path('', views.post_list, name='home'),
    path('board/<int:pk>/', views.post_list, name='post_list'),
    path('board/<str:tag>/', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:pk>/remove/', views.post_remove, name='post_remove'),
    path('post/<int:pk>/like/', views.post_like, name='post_like'),
    path('post/<int:pk>/dislike/', views.post_dislike, name='post_dislike'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('me/', views.my_info, name='my_info'),
    path('me/make', views.make_account, name='make_account'),
]

soundarchive/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('board.urls')),
    path('accounts/', include('board.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models
from django.utils import timezone
from jsonfield import JSONField


class Category(models.Model):
    name = models.CharField(max_length=100)
    post_count = models.IntegerField(default=0)

    def refresh_count(self):
        posts = Post.objects.filter(category__exact=self.id)
        self.post_count = len(posts)
        self.save()

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100)
    post_id_list = models.TextField(blank=True)
    post_count = models.IntegerField(default=0)

    def is_post_listed(self, post):
        post_id_split = list(filter(None, self.post_id_list.split('#')))
        if post in post_id_split:
            return True
        else:
            return False

    def add_post(self, post):
        new = '#'+post
        self.post_id_list += new
        self.post_count += 1
        self.save()
    
    def refresh_count(self):
        post_id_split = list(filter(None, self.post_id_list.split('#')))
        for post in post_id_split:
            try:
                old = Post.objects.get(id__exact=int(post))
                if not old.is_tag_listed(self.name):
                    post_id_split.remove(post)
            except Post.DoesNotExist:
                post_id_split.remove(post)
        self.post_id_list = '#'+'#'.join(post_id_split)
        self.post_count = len(post_id_split)
        self.save()

    def get_posts(self):
        self.refresh_count()
        post_id_split = list(filter(None, self.post_id_list.split('#')))
        posts = Post.objects.filter(id__in=post_id_split).order_by('-like')
        return posts

    def __str__(self):
        return self.name


def upload_audio(instance, filename):
    return 'board/%s/%s/%s' % (instance.author, str(timezone.localtime()).replace(':',''), filename)


class Post(models.Model):
    author = models.ForeignKey('auth.User', related_name='posts', on_delete=models.CASCADE)
    category = models.ForeignKey('board.Category', related_name='posts', default=0, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    text = models.TextField()
    audio_file = models.FileField(blank=True, upload_to=upload_audio)
    created_date = models.DateTimeField(default=timezone.localtime)
    published_date = models.DateTimeField(blank=True, null=True)

    like = models.IntegerField(default=0)
    dislike = models.IntegerField(default=0)

    like_list = models.TextField(blank=True)
    dislike_list = models.TextField(blank=True)
    tag_list = models.TextField(blank=True)

    def publish(self):
        self.published_date = timezone.localtime()
        self.save()

    def liked(self, new):
        like_split = list(filter(None, self.like_list.split(',')))
        dislike_split = list(filter(None, self.dislike_list.split(',')))
        if new not in like_split :
            if len(like_split) > 0 :
                self.like_list += ','
            self.like_list += new
            self.like += 1
            self.save()
        if new in dislike_split :
            dislike_split.remove(new)
            self.dislike_list = ','.join(dislike_split)
            self.dislike -= 1
            self.save()

    def disliked(self, new):
        like_split = list(filter(None, self.like_list.split(',')))
        dislike_split = list(filter(None, self.dislike_list.split(',')))
        if new not in dislike_split :
            if len(dislike_split) > 0 :
                self.dislike_list += ','
            self.dislike_list += new
            self.dislike += 1
            self.save()
        if new in like_split :
            like_split.remove(new)
            self.like_list = ','.join(like_split)
            self.like -= 1
            self.save()

    def add_tag(self):
        tag_split = list(filter(None, self.tag_list.split('#')))
        formatted_list = ''
        for i in range(len(tag_split)) :
            tag_split[i] = tag_split[i].strip()
            try:
                old = Tag.objects.get(name__exact=tag_split[i])
                if not old.is_post_listed(str(self.id)) :
                    old.add_post(str(self.id))
            except Tag.DoesNotExist:
                new = Tag(name=tag_split[i])
                new.add_post(str(self.id))
            formatted_list += '#'+tag_split[i]+' '
        self.tag_list = formatted_list
        self.save()

    def is_tag_listed(self,tag):
        tag_split = list(filter(None, self.tag_list.split('#')))
        tag += ' '
        if tag in tag_split :
            return True
        else :
            return False
        
    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey('board.Post', related_name='comments', on_delete=models.CASCADE)
    author = models.CharField(max_length=50)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.localtime)

    def __str__(self):
        return self.text


class CoinAccount(models.Model):
    owner = models.ForeignKey('auth.User', related_name='coin', on_delete=models.CASCADE)
    block = JSONField(default="{}")
    created_date = models.DateTimeField(default=timezone.localtime)

board/forms.py
from django import forms
from .models import Post
from django.contrib.auth.models import User

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('category', 'title', 'text', 'audio_file', 'tag_list')
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'enter title here'}),
            'text': forms.Textarea(attrs={'placeholder': 'enter description here'}),
            'tag_list': forms.TextInput(attrs={'placeholder': '#add #hashtag #freely'}),
        }
        labels = {
            'category': 'Category',
            'title': 'Title',
            'text': 'Description',
            'audio_file': 'Audio file',
            'tag_list': '#hashtag',
        }

board/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from django.urls import reverse_lazy
from django.views import generic
from .models import Post, Category, Tag, CoinAccount
from .forms import PostForm
import requests
import json


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

def post_list(request, pk=0, tag=''):
    categories = Category.objects.all().order_by('id')
    for c in categories:
        c.refresh_count()
    tags = Tag.objects.all().order_by('id')
    for t in tags:
        t.refresh_count()
    if pk and not tag:
        selected_category = Category.objects.get(id__exact=pk)
        selected_tag = ''
        posts = Post.objects.filter(category__exact=selected_category).order_by('-like')
    elif tag:
        selected_category = 0
        selected_tag = Tag.objects.get(name__exact=tag)
        posts = selected_tag.get_posts()
    else:
        selected_category = 0
        selected_tag = ''
        posts = Post.objects.all().order_by('-created_date')
    return render(request, 'board/post_list.html', {
            'posts': posts, 
            'categories': categories, 
            'tags': tags,
            'selected_category': selected_category,
            'selected_tag': selected_tag})

def post_detail(request, pk):
    categories = Category.objects.all().order_by('id')
    tags = Tag.objects.all().order_by('id')
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'board/post_detail.html', {
            'post': post, 'tags': tags, 'categories': categories})

@login_required
def post_new(request):
    categories = Category.objects.all().order_by('id')
    tags = Tag.objects.all().order_by('id')
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.localtime()
            post.save()
            post.add_tag()
            block_text = requests.get("http://localhost:5002/mine/").text
            print(block_text)
            new_block = json.loads(block_text)
            CoinAccount.objects.create(
                owner=post.author,
                block=new_block
            ).save()
            return redirect('board:post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'board/post_edit.html', {
            'form': form, 'tags': tags, 'categories': categories})

@login_required
def post_edit(request, pk):
    categories = Category.objects.all().order_by('id')
    tags = Tag.objects.all().order_by('id')
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            #post.author = request.user
            post.published_date = timezone.localtime()
            post.add_tag()
            #post.save()
            return redirect('board:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'board/post_edit.html', {
            'form': form, 'tags': tags, 'categories': categories})

@login_required
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('board:post_list')

@login_required
def post_like(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.liked(request.user.username)
    return redirect('board:post_detail', pk=post.pk)

@login_required
def post_dislike(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.disliked(request.user.username)
    return redirect('board:post_detail', pk=post.pk)

@login_required
def my_info(request):
    categories = Category.objects.all().order_by('id')
    tags = Tag.objects.all().order_by('id')
    my_posts = Post.objects.filter(author__exact=request.user).order_by('-created_date')
    my_score = 0
    for post in my_posts:
        my_score += post.like
    try:
        my_account = CoinAccount.objects.filter(owner__exact=request.user).values_list('block')
    except CoinAccount.DoesNotExist:
        my_account = 0
    print(my_account)
    # if request.method == "POST":
    return render(request, 'board/my_info.html', {
            'my_account': len(my_account),
            'my_posts': my_posts, 
            'my_score': my_score, 
            'tags': tags, 'categories': categories})

@login_required
def make_account(request):
    categories = Category.objects.all().order_by('id')
    tags = Tag.objects.all().order_by('id')
    my_account = CoinAccount(owner=request.user,address='JUST_SOME_ADDRESS')
    my_account.save()
    my_posts = Post.objects.filter(author__exact=request.user).order_by('-created_date')
    my_score = 0
    for post in my_posts:
        my_score += post.like
    return render(request, 'board/my_info.html', {
            'my_account': my_account, 
            'my_posts': my_posts, 
            'my_score': my_score, 
            'tags': tags, 'categories': categories})

board/templates/board/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <title>SoundArchive-TEST</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/regular.css" integrity="sha384-IG162Tfx2WTn//TRUi9ahZHsz47lNKzYOp0b6Vv8qltVlPkub2yj9TVwzNck6GEF" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/fontawesome.css" integrity="sha384-4aon80D8rXCGx9ayDt85LbyUHeMWd3UiBaWliBlJ53yzm9hqN21A+o1pqoyK04h+" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/board.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="{% url 'board:home' %}">SoundArchive</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'board:home' %}">Home</a>
                </li>
                {% block dropdown %}
                {% endblock %}
            </ul>
            <ul class="navbar-nav mt-2 mt-md-0 mr-sm-2">
                {% if user.is_authenticated %}
                <li class="nav-item active"><a class="nav-link" href="{% url 'board:my_info' %}"><span class="far fa-user"></span> {{ user.username }}</a></li>
                <li><a class="btn btn-outline-primary my-2 my-sm-0 mr-sm-1" href="{% url 'board:post_new' %}" role="button">New Post</a></li>
                <li><a class="btn btn-outline-danger my-2 my-sm-0" href="{% url 'logout' %}" role="button">Sign out</a></li>
                {% else %}
                <li><a class="btn btn-outline-warning my-2 my-sm-0" href="{% url 'login' %}" role="button">Sign in</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <main role="main" class="wrapper">
        {% block content %}
        {% endblock %}
    </main>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!--<script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js" integrity="sha384-0pzryjIRos8mFBWMzSSZApWtPl/5++eIfzYmTgBBmXYdhvxPc+XcFEk+zJwDgWbP" crossorigin="anonymous"></script>-->
</body>
</html>

board/templates/board/base2.html
{% load static %}
<!DOCTYPE html>
<html>

<!-- 사이트 디자인 참조
https://bootstrapious.com/p/bootstrap-sidebar 
https://getbootstrap.com/docs/4.3/getting-started/introduction/
-->

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>căno</title>
    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/board2.css' %}">
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js" integrity="sha384-0pzryjIRos8mFBWMzSSZApWtPl/5++eIfzYmTgBBmXYdhvxPc+XcFEk+zJwDgWbP" crossorigin="anonymous"></script>

</head>

<body>
    <div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3><a href="{% url 'board:home' %}">căno</a></h3>
            </div>

            <ul class="list-unstyled components">
                {% block sidebar %}
                {% endblock %}
            </ul>
        </nav>

        <!-- Page Content  -->
        <div id="content">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
                <div class="container-fluid">
                    {% comment %} 
                    <button type="button" id="sidebarCollapse" class="btn btn-info">
                        <i class="fas fa-align-left"></i>
                        <span>Toggle Sidebar</span>
                    </button>
                    {% endcomment %}
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav navbar-nav">
                            <li class="nav-item"><a class="nav-link" href="{% url 'board:home' %}"><i class="fas fa-home"></i></a></li>
                            {% block topnav %}
                            {% endblock %}
                        </ul>
                        <ul class="nav navbar-nav ml-auto">
                            {% if user.is_authenticated %}
                                <li class="nav-item active"><a class="nav-link" href="{% url 'board:my_info' %}"><i class="fas fa-user"></i> {{ user.username }}</a></li>
                                <li><a class="btn btn-outline-primary my-2 my-sm-0 mr-sm-1" href="{% url 'board:post_new' %}" role="button">New Post</a></li>
                                <li><a class="btn btn-outline-danger my-2 my-sm-0" href="{% url 'logout' %}" role="button">Sign out</a></li>
                            {% else %}
                                <li><a class="btn btn-outline-warning my-2 my-sm-0" href="{% url 'login' %}" role="button">Sign in</a></li>
                            {% endif %}
                        </ul>
                    </div>
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button>
                </div>
            </nav>
            {% block content %}
            {% endblock %}
        </div>
    </div>

    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!-- jQuery Custom Scroller CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>
    
    <script type="text/javascript">
        $(document).ready(function () {
            $("#sidebar").mCustomScrollbar({
                theme: "minimal"
            });

            $('#sidebarCollapse').on('click', function () {
                $('#sidebar, #content').toggleClass('active');
                $('.collapse.in').toggleClass('in');
                $('a[aria-expanded=true]').attr('aria-expanded', 'false');
            });
        });
    </script>
</body>

</html>

board/templates/board/my_info.html
{% extends 'board/base2.html' %}

{% block sidebar %}
    <li>
        <a href="#catSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Category</a>
        <ul class="collapse list-unstyled" id="catSubmenu">
            {% for cat in categories %}
                <li>
                    <a class="d-flex justify-content-between align-items-center" href="{% url 'board:post_list' pk=cat.id %}">
                        <span>{{ cat.name }}</span>
                        <span class="badge badge-light badge-pill mr-3">{{ cat.post_count }}</span>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </li>
    <li>
        <a href="#tagSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Hashtag</a>
        <ul class="collapse list-unstyled" id="tagSubmenu">
            {% for tag in tags %}
                <li>
                    <a class="d-flex justify-content-between align-items-center" href="{% url 'board:post_list' tag=tag.name %}">
                        <span>#{{ tag.name }}</span>
                        <span class="badge badge-light badge-pill mr-3">{{ tag.post_count }}</span>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </li>
{% endblock %}

{% block topnav %}
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle-split" href="#" id="dropdown1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Category</a>
        <div class="dropdown-menu scrollable-menu" aria-labelledby="dropdown1">
            {% for cat in categories %}
                <a class="dropdown-item" href="{% url 'board:post_list' pk=cat.id %}">
                    <div class="d-flex justify-content-between align-items-center">
                        <span>{{ cat.name }}</span>
                        <span class="badge badge-secondary badge-pill">{{ cat.post_count }}</span>
                    </div>
                </a>
            {% endfor %}
        </div>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle-split" href="#" id="dropdown2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Hashtag</a>
        <div class="dropdown-menu scrollable-menu" aria-labelledby="dropdown2">
            {% for tag in tags %}
                <a class="dropdown-item " href="{% url 'board:post_list' tag=tag.name %}">
                    <div class="d-flex justify-content-between align-items-center">
                        <span>#{{ tag.name }}</span>
                        <span class="badge badge-secondary badge-pill">{{ tag.post_count }}</span>
                    </div>
                </a>
            {% endfor %}
        </div>
    </li>
{% endblock %}

{% block content %}
    <h2><small>안녕하세요!</small> {{ user.username }}<small>님!</small></h2>
    {% if my_account %}
        <p>나의 가상화폐 갯수 : {{ my_account }}개</p>
    {% else %}
        <p>계좌를 가지고 있지 않아요!  <a href="{% url 'board:make_account'%}" class="btn btn-sm btn-primary">계좌번호 생성</a></p>
    {% endif %}
        <p>내가 올린 포스트 : {{ my_posts|length }}</p>
        <p>내가 받은 추천 : {{ my_score }}</p>
    {% comment %} 
        <form method="post" action="{% url 'board:my_info' %}"> {% csrf_token %}
        </form> 
    {% endcomment %}
{% endblock %}

board/templates/board/post_detail.html
{% extends 'board/base2.html' %}

{% block sidebar %}
    <li>
        <a href="#catSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Category</a>
        <ul class="collapse list-unstyled" id="catSubmenu">
            {% for cat in categories %}
                <li>
                    <a class="d-flex justify-content-between align-items-center" href="{% url 'board:post_list' pk=cat.id %}">
                        <span>{{ cat.name }}</span>
                        <span class="badge badge-light badge-pill mr-3">{{ cat.post_count }}</span>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </li>
    <li>
        <a href="#tagSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Hashtag</a>
        <ul class="collapse list-unstyled" id="tagSubmenu">
            {% for tag in tags %}
                <li>
                    <a class="d-flex justify-content-between align-items-center" href="{% url 'board:post_list' tag=tag.name %}">
                        <span>#{{ tag.name }}</span>
                        <span class="badge badge-light badge-pill mr-3">{{ tag.post_count }}</span>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </li>
{% endblock %}

{% block topnav %}
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle-split" href="#" id="dropdown1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Category</a>
        <div class="dropdown-menu scrollable-menu" aria-labelledby="dropdown1">
            {% for cat in categories %}
                {% if cat == post.category %}
                <a class="dropdown-item active" href="{% url 'board:post_list' pk=cat.id %}">
                {% else %}
                <a class="dropdown-item" href="{% url 'board:post_list' pk=cat.id %}">
                {% endif %}
                    <div class="d-flex justify-content-between align-items-center">
                        <span>{{ cat.name }}</span>
                        <span class="badge badge-secondary badge-pill">{{ cat.post_count }}</span>
                    </div>
                </a>
            {% endfor %}
        </div>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle-split" href="#" id="dropdown2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Hashtag</a>
        <div class="dropdown-menu scrollable-menu" aria-labelledby="dropdown2">
            {% for tag in tags %}
                <a class="dropdown-item " href="{% url 'board:post_list' tag=tag.name %}">
                    <div class="d-flex justify-content-between align-items-center">
                        <span>#{{ tag.name }}</span>
                        <span class="badge badge-secondary badge-pill">{{ tag.post_count }}</span>
                    </div>
                </a>
            {% endfor %}
        </div>
    </li>
{% endblock %}

{% block content %}
    <div class="post">
        <div class="date">
            {{ post.created_date }}
        </div>
        <h2>
            {{ post.title }}
            <small><i class="fas fa-tag"></i>{{ post.category }}  <i class="fas fa-user-edit"></i>{{ post.author }}</small>
        </h2>
        <p>
        {% if post.audio_file %}
            <audio controls style="width:100%; max-width:600px">
                <source src="{{ post.audio_file.url }}">
            </audio>
        {% else %}
            <p>[Audio file NOT uploaded]</p>
        {% endif %}
        </p>
        <p>{{ post.text|linebreaksbr }}</p>
        <div class="line"></div>
        <p>Tags : {{ post.tag_list }}</p>
        <p>Liked by [{{ post.like }}] : {{ post.like_list }}</p>
        <p>Disliked by [{{ post.dislike }}] : {{ post.dislike_list }}</p>
        {% if user.is_authenticated %}
            <p>
            {% if user.is_superuser or user == post.author %}
            <a class="btn btn-lg btn-default" href="{% url 'board:post_edit' pk=post.pk %}"><i class="fas fa-edit"></i></a>
            <a class="btn btn-lg btn-default" href="{% url 'board:post_remove' pk=post.pk %}"><i class="fas fa-trash-alt"></i></a>
            {% endif %}
            <a class="btn btn-lg btn-default" href="{% url 'board:post_like' pk=post.pk %}"><i class="fas fa-thumbs-up"></i> {{ post.like }}</a>
            <a class="btn btn-lg btn-default" href="{% url 'board:post_dislike' pk=post.pk %}"><i class="fas fa-thumbs-down"></i> {{ post.dislike }}</a>
            </p>
        {% endif %}
    </div>
{% endblock %}